### ISSUE TITLE
Where are the "DM_*" objects?

### ISSUE THREAD

**Issue by metaphorz** [dnlmc/lm_ooc#1]
Thanks for the logistic map implementation. I may have missed it in reading  your materials, but the 
DM_ objects are not present in LM_OOC (or I could not find them). They are coded in a brown color, indicating, they are unknown to Max. Are they in an external somewhere else? Thanks again.

**Comment by dnlmc** [comment]
Hey! Thanks for checking it out.  I realized after I posted it that I ended up using 'abstractions' for the subpatches (basically just separately saved versions of patches), rather than the strict patcher object subpatch method.

I'll reimplement the subpatches as true subpatches & then they should carry over in the text-based share method. I'll try to have it reposted sometime this weekend.

Thanks again.

**Comment by dnlmc** [comment]
@metaphorz just commited complete version, should be good to go
